# .design.system.ai
# Angular + Ionic + CSS

meta:
  name: ReShop
  version: 1.0.0
  lastUpdated: 2024-08-16

# 1. COLOR TOKENS  (WCAG 2.1 AA)
colors:
  primary:
    50: "#F3F0FF"
    100: "#E8E2FF"
    200: "#D3C6FD"
    300: "#B29FFB"
    400: "#8B7BF6"
    500: "#6B4EFF" # brand purple
    600: "#5538DB"
    700: "#452DB3"
    800: "#37278F"
    900: "#2B2173"
  secondary:
    50: "#E6FAF3"
    500: "#05D69B" # mint
    700: "#00B481"
  neutral:
    0: "#FFFFFF"
    50: "#F9FAFB"
    100: "#F3F4F6"
    200: "#E5E7EB"
    300: "#D1D5DB"
    400: "#9CA3AF"
    500: "#6B7280"
    600: "#4B5563"
    700: "#374151"
    800: "#1F2937"
    900: "#111827"
  semantic:
    success: "#05D69B"
    warning: "#F59E0B"
    error: "#EF4444"

# 2. TYPOGRAPHY
typography:
  fontFamily:
    primary: "Inter, system-ui, sans-serif"
    mono: "JetBrains Mono, monospace"
  scales:
    h1: { size: 32, weight: 700, line: 1.2 } # page titles
    h2: { size: 28, weight: 600, line: 1.3 }
    h3: { size: 24, weight: 600, line: 1.35 }
    h4: { size: 20, weight: 600, line: 1.4 }
    body1: { size: 16, weight: 400, line: 1.5 }
    body2: { size: 14, weight: 400, line: 1.43 }
    caption: { size: 12, weight: 500, line: 1.33 }

# 3. SPACING (8-pt grid)
space:
  xs: 4px
  sm: 8px
  md: 16px
  lg: 24px
  xl: 32px
  2xl: 48px
  3xl: 64px

# 4. ELEVATION (shadows)
elevation:
  sm: "0 1px 2px 0 rgba(0,0,0,0.05)"
  md: "0 4px 6px -1px rgba(0,0,0,0.1), 0 2px 4px -1px rgba(0,0,0,0.06)"
  lg: "0 10px 15px -3px rgba(0,0,0,0.1), 0 4px 6px -2px rgba(0,0,0,0.05)"
  xl: "0 20px 25px -5px rgba(0,0,0,0.1), 0 10px 10px -5px rgba(0,0,0,0.04)"

# 5. BORDER RADIUS
borderRadius:
  sm: 4px
  md: 8px
  lg: 12px
  xl: 16px
  full: 50%

# 6. BREAKPOINTS (Ionic defaults)
breakpoints:
  xs: 0
  sm: 576
  md: 768
  lg: 992
  xl: 1200

###############################################################################
# 7. ANGULAR + IONIC COMPONENT RULES
###############################################################################
components:
  ion-button:
    size: large # 48 px height
    shape: round
    fill: solid
    color: primary-500
    shadow: elevation.md
    font: body1
    minWidth: 120px

  ion-card:
    background: neutral-0
    borderRadius: lg
    shadow: elevation.md
    padding: space.md

  ion-modal:
    --height: auto
    --width: 90%
    --max-width: 420px
    backdropDismiss: true
    enterAnimation: ios
    leaveAnimation: ios

  ion-input / ion-item:
    labelPlacement: floating
    color: neutral-700
    borderRadius: md
    --padding-start: space.sm
    --padding-end: space.sm

  ion-spinner:
    color: primary-500
    size: small

###############################################################################
# 8. CSS CUSTOM PROPERTIES (auto-generated CSS file)
###############################################################################
scssTokens: |
  /* generated by AI from .design.system.ai */
  :root {
    --color-primary: #6B4EFF;
    --color-secondary: #05D69B;
    --color-success: #05D69B;
    --color-warning: #F59E0B;
    --color-error: #EF4444;

    --font-primary: 'Inter', system-ui, sans-serif;
    --font-mono: 'JetBrains Mono', monospace;

    --space-xs: 4px;
    --space-sm: 8px;
    --space-md: 16px;
    --space-lg: 24px;
    --space-xl: 32px;
    --space-2xl: 48px;
    --space-3xl: 64px;

    --radius-sm: 4px;
    --radius-md: 8px;
    --radius-lg: 12px;
    --radius-xl: 16px;
    --radius-full: 50%;

    --shadow-sm: 0 1px 2px 0 rgba(0,0,0,0.05);
    --shadow-md: 0 4px 6px -1px rgba(0,0,0,0.1), 0 2px 4px -1px rgba(0,0,0,0.06);
    --shadow-lg: 0 10px 15px -3px rgba(0,0,0,0.1), 0 4px 6px -2px rgba(0,0,0,0.05);
    --shadow-xl: 0 20px 25px -5px rgba(0,0,0,0.1), 0 10px 10px -5px rgba(0,0,0,0.04);
  }
